### ISSUE TITLE
KMM feature to leverage in-tree dependencies via symlink not working

### ISSUE THREAD

**Issue by hershpa** [rh-ecosystem-edge/kernel-module-management#1036]
### Summary:
Using KMM 2.0.2, we observed depmod fails to generate the correct dependency list via the symlink for in-tree dependencies. As a result, we still need to copy in-tree kmods to driver container. 

### Goal: 
Only copy out of tree kmods in driver container image with PR https://github.com/intel/intel-data-center-gpu-driver-for-openshift/pull/79.

### Details:
PR used to test: https://github.com/intel/intel-data-center-gpu-driver-for-openshift/pull/79

The following was observed in build log:
[2/2] STEP 18/20: RUN depmod -b /opt ${KERNEL_FULL_VERSION}
 depmod: ERROR: fstatat(3, host): No such file or directory

Specifically with the symlink, KMM fails to load out of tree compat.ko because the dependency list is erroneously empty which is confirmed by `cat modules.dep | grep compat`.

Without symlink, the dependency list is correct:

`sh-5.1# cat modules.dep | grep compat.ko:
updates/compat/compat.ko: kernel/drivers/gpu/drm/display/drm_display_helper.ko.xz kernel/drivers/media/cec/core/cec.ko.xz kernel/drivers/gpu/drm/drm_kms_helper.ko.xz kernel/drivers/video/fbdev/core/syscopyarea.ko.xz kernel/drivers/video/fbdev/core/sysfillrect.ko.xz kernel/drivers/video/fbdev/core/sysimgblt.ko.xz kernel/drivers/video/fbdev/core/fb_sys_fops.ko.xz kernel/drivers/gpu/drm/drm.ko.xz`

Note: The .ko.xz files are the in-tree deps.

Short-term workaround which has a smaller optimization of only copying necessary out of tree and in-tree kmods: https://github.com/intel/intel-data-center-gpu-driver-for-openshift/pull/81

**Comment by mregmi** [comment]
The reason depmod is not working in symlink method is that /lib/modules/<kernel version> does not have any files. it needs to be mounted from host or installed in the pod itself. Currently we use ubi-minimal on 2nd stage and that folder is empty. it probably works when using ubuntu image which has modules installed or when using dtk image.
