### ISSUE TITLE
Loading multiple modules

### ISSUE THREAD

**Issue by lmu-silicom** [rh-ecosystem-edge/kernel-module-management#488]
I have a driver container image with many drivers and I like to have all of them loaded. How can I do that with KMM? Can KMM call a script to load/unload the drivers?

Thanks

**Comment by qbarrand** [comment]
Hi @lmu-silicom! KMM does not support that in 1.0 but this is being worked on upstream: https://github.com/kubernetes-sigs/kernel-module-management/issues/295

**Comment by qbarrand** [comment]
This feature is not available in KMM for OpenShift v1.1.0, released on 2023-06-28.
