### ISSUE TITLE
FW load feature availability on KMMO for OCP

### ISSUE THREAD

**Issue by hershpa** [rh-ecosystem-edge/kernel-module-management#49]
When will FW load feature from upstream [https://github.com/kubernetes-sigs/kernel-module-management/pull/17] be available on downstream KMMO repo for OCP?

**Comment by qbarrand** [comment]
Hi @hershpa, that was backported in https://github.com/rh-ecosystem-edge/kernel-module-management/pull/52. Closing this issue.
