### ISSUE TITLE
KMM operator not available for OKD 4.11 & also not supported on 4.12 

### ISSUE THREAD

**Issue by fayazahamedj** [rh-ecosystem-edge/kernel-module-management#614]
Hello Team, 

While installing kmm operator on OKD 4.11 via below link as KMM operator not available, kmm-operator-controller-manager pod is going to CrashLoopBackoff state & primarily getting below error. 

$ oc get clusterversion
NAME      VERSION                          AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.11.0-0.okd-2023-01-14-152430
$ oc apply -k https://github.com/rh-ecosystem-edge/kernel-module-management/config/default

Error on kmm-operator-controller-manager pod: 
E0609 08:53:24.887484       1 controller.go:329] kmm "msg"="Reconciler error" "error"="could not get node hyd-okd-edge005 osImageVersion" "Node"={"name":"hyd-okd-edge005"} "controller"="NodeKernel" "controllerGroup"="" "controllerKind"="Node" "name"="hyd-okd-edge005" "namespace"="" "reconcileID"="83d7723a-3595-4193

Do let know if you require any further logs...

Regards,
Fayaz

**Comment by ybettan** [comment]
@qbarrand This is exactly the reason I had suggested @fayazahamedj to try to install https://github.com/kubernetes-sigs/kernel-module-management instead seems some changes must be done in the code to work on OKD, but after discussing in slack seems like the u/s version has it own issues while deployed on OKD.

**Comment by yevgeny-shnaidman** [comment]
I don't think that we need to create a separate image for OKD just because of one issue. The logging of error (or warning) seems ok, since in case there is an issue with DTK on OCP , it will be found during Build.

**Comment by bthurber** [comment]
Propose closing this.  @qbarrand
