### ISSUE TITLE
Make KMMO seLinux option type tighter to insert/remove OOT kernel modules.

### ISSUE THREAD

**Issue by hershpa** [rh-ecosystem-edge/kernel-module-management#63]
KMMO uses seLinux option [spc_t](https://danwalsh.livejournal.com/74754.html) (super privileged container type) for daemonSet which may be over-privileged to insert/remove the OOT kernel modules. We would like to explore if there is a tighter seLinux policy we can use instead. One particular option we would like to try is the [user-container-selinux](https://github.com/intel/user-container-selinux). Is there an interface available in module yaml to try this seLinux policy instead of default spc_t?

**Comment by qbarrand** [comment]
Closing in favor of https://github.com/kubernetes-sigs/kernel-module-management/issues/100.
