### ISSUE TITLE
removing a kernel module as a pre-requisite in KMMO

### ISSUE THREAD

**Issue by mregmi** [rh-ecosystem-edge/kernel-module-management#64]
Hello, Is there a way to tell the KMMO to remove a certain kernel module before we load ours? In a OOT driver we are currently working on, we need to remove the in tree driver before we load ours. Thanks
To elaborate, in order to insert our OOT graphics driver, we first need to remove in tree drm driver or else the insert will fail. if there no current functionality to do this before insert, a way to run a pre-requisite commands/scripts would be a good idea.

**Comment by qbarrand** [comment]
Hi @mregmi, would you kind moving this issue to https://github.com/kubernetes-sigs/kernel-module-management/issues?

**Comment by mregmi** [comment]
Sure, I will close this and open in upstream.
