### ISSUE TITLE
KMM Day1 should support scratch images

### ISSUE THREAD

**Issue by yevgeny-shnaidman** [rh-ecosystem-edge/kernel-module-management#910]
in KMM V2.0, the drivers containers image are recommended to be scratched ( minimal images, no need for any packages to be installed, only .ko files). In Day1 package code, we rely on modprobe executable being present in the drivers container image. Since we recommend that the same image that is used for Day2 can also be used for day1, we need to see how this issue can be solved. One possible solution: mapped host /usr/sbin directory into the running container

**Comment by qbarrand** [comment]
Unfortunately as of today Red Hat can only certify container images based on UBI. That includes kmod images, so downstream we should not recommend images based on `scratch`, but rather something like [ubi9-micro](https://catalog.redhat.com/software/containers/ubi9/ubi-micro/615bdf943f6014fa45ae1b58).

> One possible solution: mapped host /usr/sbin directory into the running container

Is the `kmod` package guaranteed to be installed on hosts?

**Comment by yevgeny-shnaidman** [comment]
I think it is pretty guaranteed, that kmod will be installed on an Openshift node. At the very least, it is more reliable to count on it to be installed on the node, than to count on it to be installed on the ubi-micro images, especially if somewhere in the future we/customer can move to the scratch images
