### ISSUE TITLE
DaemonSet takes 10mins to show up after build complete

### ISSUE THREAD

**Issue by hershpa** [rh-ecosystem-edge/kernel-module-management#99]
Issue Summary:
The DaemonSet does not show up immediately after the driver container build is complete on OCP. It take 10 mins for the DaemonSet to show up. What is the reason for this delay?

Suggested Priority(P1-P3) & Urgent(Urgent, medium, Low):
P1 and medium

**Comment by qbarrand** [comment]
Tracked as Red Hat issue [MGMT-12521](https://issues.redhat.com/browse/MGMT-12521).

**Comment by hershpa** [comment]
Hi @qbarrand, we cannot access that Red Hat issue link, can we get access to it?
